---
- hosts: wp
  become: true

  roles:
    - { role: mariadb, tags: [ 'mariadb' ] }
    - apache2
    - { role: wordpress, tags: [ 'wordpress' ] }
    - { role: migracion, tags: [ 'migracion' ] }
    - { role: plugins, tags: [ 'plugins' ] }