---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Restaurar dump de la db en database
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    state: import
    target: "/tmp/{{ backup_db }}"

- name: Migrar sitio
  ansible.builtin.unarchive:
    src: "/tmp/{{ backup_sitio }}"
    dest: /var/www
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    remote_src: true
    extra_opts: --strip-components=2

- name: Actualizar clave para conexion db
  ansible.builtin.lineinfile:
    path: "/var/www/{{ server_name }}/public/wp-config.php"
    regexp: "define\\( 'DB_PASSWORD', '(.)+' \\);"
    line: "define('DB_PASSWORD', '{{ mysql_password }}');"
  notify: servicios_apache

## actualizar site_url + home en db para sitio migrado
- name: Fix para cambiar nuevo sitio en db wordpress
  community.mysql.mysql_query:
    login_db: "{{ mysql_db }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query:
    - UPDATE wp_options SET option_value='http://{{ server_name }}' WHERE option_name='siteurl'
    - UPDATE wp_options SET option_value='https://{{ server_name }}' WHERE option_name='home'
    single_transaction: true
  notify: servicios_apache 