---
- name: Recargar Apache
  service:
    name: apache2
    state: reloaded
  listen: servicios_apache

- name: Reiniciar Apache
  service:
    name: apache2
    state: restarted
  listen: servicios_apache